volumes:
  ollama-data:

services:

  big-brother:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Paris"
    env_file:
      - ./.env

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama-data:/root/.ollama
