volumes:
  postgres-data:
  ollama-data:

services:

  big-brother:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Paris"
    env_file:
      - ./.env
    depends_on:
      - bigbrother-postgres
      - ollama

  bigbrother-postgres:
    extends:
      file: postgres/docker-compose.yml
      service: bigbrother-postgres

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama-data:/root/.ollama
