volumes:
  bigbrother-postgres-data:
  ollama-data:

services:

  bigbrother:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: "Europe/Paris"
    env_file:
      - ./.env
    depends_on:
      - bigbrother-postgres
      - ollama

  bigbrother-postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/
    expose:
      - 5432

  ollama:
    image: ollama/ollama
    volumes:
      - ollama-data:/root/.ollama
    expose:
      - 11434
